/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "local.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#include "esclavo.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#define TAM 5

static void
local_sx_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int getidslove_1_arg;
		int getnomslove_1_arg;
		int getdirslove_1_arg;
		int getlecslove_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case getIdLocal:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) getidlocal_1_svc;
		break;

	case getId_esclavos:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_idEsclavos_sx;
		local = (char *(*)(char *, struct svc_req *)) getid_esclavos_1_svc;
		break;

	case getIdSlove:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) getidslove_1_svc;
		break;

	case getNomSlove:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) getnomslove_1_svc;
		break;

	case getDirSlove:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) getdirslove_1_svc;
		break;

	case getLecSlove:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) getlecslove_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

void salir() {
	clnt_destroy (esclavos[0]);
	clnt_destroy (esclavos[1]);
	clnt_destroy (esclavos[2]);
	clnt_destroy (esclavos[3]);
	clnt_destroy (esclavos[4]);

}



int
main (int argc, char **argv)
{


	
	char ip[20];
	
	int opcion=-1, indice=0, dirLocal, local=0;
	while(opcion!=0)
    	{
		
		printf("======== MENU DE OPCIONES SERVIDOR LOCAL ========\n");
		printf("1.- Ingresar la ID de este maestro local.\n");
		if(local!=0)
			printf("2.- Ingresar procesos esclavos asociados.\n");
		printf("0.- Salir.\n");
		printf("=================================================\n");
		printf("Ingrese una opción: ");
		scanf("%d",&opcion);
		switch(opcion){
			case 1:
				printf("Digite la ID de este maestro local.\n");
				scanf("%d",&dirLocal);
				local=1;
			break;
			case 2:
				if(indice==5){
					printf("Ya ingresaste los 5 procesos esclavos asociados.\n");
					break;
				}
				printf("Ingrese la ip del proceso %d esclavo asociado\n",indice);
				fflush(stdout);
				scanf("%s",&ip);
				esclavos[indice] = clnt_create (ip, ESCLAVO_SX, ESCLAVO_SX_VERSION, "udp");
				if (esclavos[indice] == NULL) {
					clnt_pcreateerror (ip);
					exit (1); 
				}
				indice++;
				
			break;
			
			case 0:	
				break;
			
			default: printf("Opcion no valida.\n");
		}
	}
	
	

	register SVCXPRT *transp;

	pmap_unset (LOCAL_SX, LOCAL_SX_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, LOCAL_SX, LOCAL_SX_VERSION, local_sx_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (LOCAL_SX, LOCAL_SX_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, LOCAL_SX, LOCAL_SX_VERSION, local_sx_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (LOCAL_SX, LOCAL_SX_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
