/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "esclavo.h"

#include <memory.h> /* for memset */
#include "local.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };


int  *result_1;
char *getidesclavo_1_arg;
char * *result_2;
char *getnomesclavo_1_arg;
char * *result_3;
char *getdiresclavo_1_arg;
float  *result_4;
char *getlecesclavo_1_arg;


int *
getidlocal_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;
	result = dirLocal;
	return &result;
}

idEsclavos_sx *
getid_esclavos_1_svc(void *argp, struct svc_req *rqstp)
{
	static idEsclavos_sx  result;
	idEsclavos_sx * idProc;
	idProc = (idEsclavos_sx*) malloc(sizeof(idEsclavos_sx));
	//idProc->idProcEsclavos = (int *)malloc(TAM*sizeof(int));
	int i;
	for(i=0;i<TAM;i++) {
		printf("%i ",i);
		fflush(stdout);
		idProc->idProcEsclavos[i]= getIdSlave(i);
		printf("dir: %i\n",idProc->idProcEsclavos[i]);
		fflush(stdout);
	}
	result = *idProc;
	return &result;
}



int getIdSlave(int i){
	result_1 = getidesclavo_1((void*)&getidesclavo_1_arg, esclavos[i]);
	if (result_1 == (int *) NULL) {
		clnt_perror (esclavos[i], "call failed");
		return -1;
	}
	return *result_1;
}

int *
getidslove_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}


float *
getlecslove_1_svc(int *argp, struct svc_req *rqstp)
{
	procesclavos_sx * esc;
	static float  result=0.1;
	int i, valor=*argp;
	for(i=0;i<TAM;i++) {
		if(getIdSlave(i)==valor){
			return getlecesclavo_1(getlecesclavo_1_arg, esclavos[i]);
		}
		
	}


	return &result;
}

char **
getnomslove_1_svc(int *argp, struct svc_req *rqstp)
{
	procesclavos_sx * esc;
	static char * result;
	int i, valor=*argp;
	for(i=0;i<TAM;i++) {
		if(getIdSlave(i)==valor){
			return getnomesclavo_1(getnomesclavo_1_arg, esclavos[i]);
		}
		
	}

	return &result;
}

char **
getdirslove_1_svc(int *argp, struct svc_req *rqstp)
{
	procesclavos_sx * esc;
	static char * result;
	int i, valor=*argp;
	for(i=0;i<TAM;i++) {
		if(getIdSlave(i)==valor){
			return getdiresclavo_1(getdiresclavo_1_arg, esclavos[i]);
		}
		
	}

	return &result;
}

