/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ESCLAVO_H_RPCGEN
#define _ESCLAVO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct procesclavos_sx {
	int idProceso;
	char *nomUsuario;
	char *direccion;
	float lectura;
};
typedef struct procesclavos_sx procesclavos_sx;
procesclavos_sx esclavo;



#define ESCLAVO_SX 0x3C000001
#define ESCLAVO_SX_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define getIdEsclavo 1
extern  int * getidesclavo_1(void *, CLIENT *);
extern  int * getidesclavo_1_svc(void *, struct svc_req *);
#define getNomEsclavo 2
extern  char ** getnomesclavo_1(void *, CLIENT *);
extern  char ** getnomesclavo_1_svc(void *, struct svc_req *);
#define getDirEsclavo 3
extern  char ** getdiresclavo_1(void *, CLIENT *);
extern  char ** getdiresclavo_1_svc(void *, struct svc_req *);
#define getLecEsclavo 4
extern  float * getlecesclavo_1(void *, CLIENT *);
extern  float * getlecesclavo_1_svc(void *, struct svc_req *);
extern int esclavo_sx_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getIdEsclavo 1
extern  int * getidesclavo_1();
extern  int * getidesclavo_1_svc();
#define getNomEsclavo 2
extern  char ** getnomesclavo_1();
extern  char ** getnomesclavo_1_svc();
#define getDirEsclavo 3
extern  char ** getdiresclavo_1();
extern  char ** getdiresclavo_1_svc();
#define getLecEsclavo 4
extern  float * getlecesclavo_1();
extern  float * getlecesclavo_1_svc();
extern int esclavo_sx_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_procesclavos_sx (XDR *, procesclavos_sx*);
extern  bool_t xdr_procesclavos_sx (XDR *, procesclavos_sx*);

#else /* K&R C */
extern bool_t xdr_procesclavos_sx ();
extern bool_t xdr_procesclavos_sx ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ESCLAVO_H_RPCGEN */
