/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "esclavo.h"

bool_t
xdr_procesclavos_sx (XDR *xdrs, procesclavos_sx *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->idProceso))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nomUsuario, 35))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->direccion, 30))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->lectura))
		 return FALSE;
	return TRUE;
}
