/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "local.h"

bool_t
xdr_proclocal_sx (XDR *xdrs, proclocal_sx *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->idProceso))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nomUsuario, 35))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->direccion, 30))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->lectura))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_idEsclavos_sx (XDR *xdrs, idEsclavos_sx *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, ( 5 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->idProcEsclavos, 5,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->idProcEsclavos;
					i < 5; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, ( 5 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->idProcEsclavos, 5,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->idProcEsclavos;
					i < 5; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->idProcEsclavos, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
